version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    build: ./redis
    volumes:
      - redis-data:/data
    env_file:
      - .env

volumes:
  redis-data:
