FROM node:18-alpine
WORKDIR /app

RUN apk add --no-cache \
    curl \
    python3 \
    py3-pip \
    ffmpeg \
    aria2

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PATH="/opt/venv/bin:$PATH"

RUN python3 -m venv /opt/venv
RUN /opt/venv/bin/pip install --no-cache-dir -U yt-dlp

COPY package*.json ./
RUN npm install

RUN mkdir -p /app/dist /app/downloads && chmod -R 777 /app/downloads /app/dist

COPY . .
RUN chown -R node:node /app

USER node
EXPOSE 3001
CMD ["npm", "run", "dev"]