# Generated by Django 4.2.5 on 2023-11-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_song_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(default=0),
        ),
    ]
